# FROM node:22

# COPY public/ public/
# COPY src/ src/
# COPY package.json package.json
# # COPY . .

# EXPOSE 8080

# RUN npm install
# RUN npm run build

# CMD ["npm", "run", "dev"]


# FROM node:22

# WORKDIR /app

# COPY public/ public/
# COPY src/ src/
# COPY package.json package.json
# COPY package-lock.json package-lock.json

# EXPOSE 5173

# RUN npm install

# RUN npm run build

# ENTRYPOINT ["npm", "run", "preview"]


# Etapa de construcción
FROM node:18-alpine as build-stage

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos de dependencias
COPY package*.json ./

# Instalar las dependencias
RUN npm install

# Copiar el resto de la aplicación
COPY . .

# Construir la aplicación
RUN npm run build

# Etapa de producción
FROM nginx:stable-alpine as production-stage

# Copiar los archivos construidos desde la etapa de construcción
COPY --from=build-stage /app/dist /usr/share/nginx/html

# Exponer el puerto que utiliza Nginx
EXPOSE 80

# Definir el comando por defecto para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]